spring:
  application:
    name: groupware
  profiles:
    active: local

# Jasypt 암호화 설정 (JasyptConfig.java에서 Bean으로 설정)
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# MyBatis 공통 설정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-fetch-size: 100
    default-statement-timeout: 30

logging:
  level:
    root: info